### ISSUE TITLE
core.py update breaks kordesii in Windows 10

### ISSUE THREAD

**Issue by tguilday** [Defense-Cyber-Crime-Center/kordesii#12]
The following update to **core.py** appears to break the `kordesii parse` command in a Windows 10 environment:
`process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=sys.platform != 'nt')`

Windows failed to interpret the command `C:\\Program Files\\IDA 7.2\\ida.exe...` as a valid command with the `shell=sys.platform != 'nt'` argument and threw the following error message:
`'C:\Program' is not recognized as an internal or external command, operable program or batch file.`

**Comment by DC3-DCCI** [comment]
This should be fixed in the 1.6.1 version.
