### ISSUE TITLE
Enable test case addition / updates when errors are encountered

### ISSUE THREAD

**Issue by ddash-ct** [Defense-Cyber-Crime-Center/kordesii#14]
Enable a command line option for `kordesii test` such that test cases can be updated/added even if an `error` is encountered and aggregated in `self.reporter.errors`, which is not always due to something related to a decoder.  

Specifically applies to the `update_tests` and `add_test` functions within `tester.Tester`

**Comment by DC3-DCCI** [comment]
This would be a good thing to add.  Something like a `-f / --force` flag would make sense.  We can add this in the next minor release unless you would like to contribute this.
