### ISSUE TITLE
MOVUPS/MOVUPD support is missing from function_tracing/opcodes

### ISSUE THREAD

**Issue by ddash-ct** [Defense-Cyber-Crime-Center/kordesii#2]
In `function_tracing/opcodes.py`, there is support for the `MOVAPD` and `MOVAPS` instructions, but no support for the `MOVUPD` and `MOVUPS` instructions.  

After evaluating, the `MOVAPD` and `MOVAPS` instructions can be combined to a single function using appropriate function decorators, and will also support the `MOVUPD` and `MOVUPS` instructions.

**Comment by DC3-DCCI** [comment]
The pull request !5 should apply these changes.
