### ISSUE TITLE
Signed values cause issues with IDIV instruction.

### ISSUE THREAD

**Issue by kmhenson-re** [Defense-Cyber-Crime-Center/kordesii#26]
While analyzing eae876886f19ba384f55778634a35a1d975414e83f22f6111e3e792f706301fe, observed unexpected values in registers after emulation specifically if an arithmetic operation is performed with negative signed values. 

- Example operands: IMUL, IDIV, LEA (there might be more)

- This causes string decryption to produce different results after emulation

- Using emulate.hook_instruction() is not viable since the instruction is still being emulated either before or after hook

- Workaround was to trap faulty operands and perform manual arithmetic operations supporting negative signed values (like doing manual emulation)

**Comment by DC3-DCCI** [comment]
This issue should be resolved now that 2.2.0 has been released.
