### ISSUE TITLE
Extracting variable names may sometimes crash kordesii

### ISSUE THREAD

**Issue by kmhenson-re** [Defense-Cyber-Crime-Center/kordesii#27]
Extracting variable names may sometimes crash kordesii. Observed while analyzing eae876886f19ba384f55778634a35a1d975414e83f22f6111e3e792f706301fe.

- Example code: var = context.variables[data_ptr]

- Example Output:
```
[*] operands        : Calculating operand: [ebp+var_9B+7] -> 0x117F7FC + 0x0*0x1 - 0x94 = 0x117F768
[!] core            : 18347880
Traceback (most recent call last):
  File "c:\github\extmir-kordesii\kordesii\core.py", line 88, in decoder_entry
    main_func()
  File "c:/github/extmir-kordesii/kordesii/decoders/conti.py", line 488, in main
    decrypt_strings_2()
  File "c:/github/extmir-kordesii/kordesii/decoders/conti.py", line 246, in decrypt_strings_2
    var = context.variables[data_ptr]
  File "c:\github\extmir-kordesii\kordesii\utils\function_tracing\variables.py", line 53, in __getitem__
    return self._variables[addr_or_name]
KeyError: 18347880
[+] core            : IDA return code = 0
----Decoded Strings----
```

- Workaround was not to rely on variable names but directly use variable addresses instead

- Example workaround: var_addr = operands[1].addr

**Comment by DC3-DCCI** [comment]
Thanks for catching this. In order to replicate the error you are receiving, can you please provide the instruction address and variable you were trying to pull or some example code?

**Comment by kmhenson-re** [comment]
We are only able to replicate this on one system. As a result, I'll close it and update if it comes up consistently.

Thanks.
