### ISSUE TITLE
Bug: cpu_context.ProcessorContext.get_value WIDE_STRING

### ISSUE THREAD

**Issue by ddash-ct** [Defense-Cyber-Crime-Center/kordesii#7]
Identified an bug in `cpu_context.ProcessorContext.get_value()` specifically when specifying the `data_type` as `function_tracing.WIDE_STRING`.  

This was specifically observed in malware sample hash `c78beff838f4c57be9044996c25eca7d`, when the `FunctionTracer` is analyzing the call to `lstrcpyW` at ea `0x4034d2`.  

The following is the sample code used to extract the data:
```Python
from kordesii.utils import function_tracing

ft = function_tracing.FunctionTracer(0x4034d2)
ctx, args = ft.get_function_args(0x4034d2)
src = args[1]
value = ctx.get_value(src, data_type=function_tracing.WIDE_STRING)
```   

Where `value` is the following: `'/\x00f\x00a\x00v\x00.\x00i\x00c\x00o'` whereas it should have trailing nulls to make it a valid UTF-16 encoded string.

**Comment by DC3-DCCI** [comment]
This should be resolved as of the 1.5.0 release.
